### ISSUE TITLE
Undefined variable: type

### ISSUE THREAD

**Issue by mikebronner** [pdepend/pdepend#311]
I'm getting the following error: (initially reported here https://github.com/AtomLinter/linter-phpmd/issues/110)

```
linter-registry.js [sm]:137 [Linter] Error running PHPMD Error: PHP Notice:  Undefined variable: type in /Users/mike/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 5563(…)
```

**Comment by DanielBadura** [comment]
Got the same error. Using PHPMD 2.6.0

```
PHP Notice:  Undefined variable: type in phar:///var/www/project/phpmd.phar/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 5563
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\AbstractASTCallable::addChild() must implement interface PDepend\Source\AST\ASTNode, null given, called in phar:///var/www/project/phpmd.phar/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php on line 189 and defined in phar:///var/www/project/phpmd.phar/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTCallable.php:143
Stack trace:
#0 phar:///var/www/project/phpmd.phar/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(189): PDepend\Source\AST\AbstractASTCallable->addChild(NULL)
#1 phar:///var/www/project/phpmd.phar/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1251): PDepend\Source\Language\PHP\PHPParserVersion70->parseCallableDeclarationAddition(Object(PDepend\Source\AST\ASTMethod))
#2 phar:///var/www/project/phpmd.phar/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1208): PDepend\So in phar:///var/www/project/phpmd.phar/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTCallable.php on line 143
```

**Comment by DanielBadura** [comment]
My error came from a method that i type hinted with `null` as a return value. This is not correct so its technically no bug from this perspective. Maybe there should be still a default case in the `parseTypeHint` method which is causing this error.

```
public function foo(): null
{
  return null;
}
```
Is now 
```
public function foo(): ?string
{
   return null;
}
```

This is also now more conform with the interface which is implemented in the class that needs this method.

**Comment by kylekatarnls** [comment]
Hi, after a quick check, it seems we don't have anymore `$type` calls that could raise such errors, please try the 2.5.2 and give the new line if it's still happening and I would re-open.
