### ISSUE TITLE
dependency failure

### ISSUE THREAD

**Issue by tvdijen** [pdepend/pdepend#368]
symfony/dependency-injection 4.2.x causes our HVVM-tests to fail:

```
phpmd-ci:
     [exec] 
     [exec] Fatal error: Uncaught Error: Class Symfony\Component\DependencyInjection\Exception\ExceptionInterface may not inherit from sealed interface (Throwable) without being in the whitelist in /home/travis/build/simplesamlphp/saml2/vendor/symfony/dependency-injection/Exception/ExceptionInterface.php:22
     [exec] Stack trace:
     [exec] #0 /home/travis/build/simplesamlphp/saml2/vendor/composer/ClassLoader.php(444): include()
     [exec] #1 /home/travis/build/simplesamlphp/saml2/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
     [exec] #2 /home/travis/build/simplesamlphp/saml2/vendor/symfony/dependency-injection/Exception/RuntimeException.php(19): Composer\Autoload\ClassLoader->loadClass()
     [exec] #3 /home/travis/build/simplesamlphp/saml2/vendor/composer/ClassLoader.php(444): include()
     [exec] #4 /home/travis/build/simplesamlphp/saml2/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
     [exec] #5 /home/travis/build/simplesamlphp/saml2/vendor/symfony/dependency-injection/Compiler/ResolveInvalidReferencesPass.php(42): Composer\Autoload\ClassLoader->loadClass()
     [exec] #6 /home/travis/build/simplesamlphp/saml2/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Symfony\Component\DependencyInjection\Compiler\ResolveInvalidReferencesPass->process()
     [exec] #7 /home/travis/build/simplesamlphp/saml2/vendor/symfony/dependency-injection/ContainerBuilder.php(748): Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
     [exec] #8 /home/travis/build/simplesamlphp/saml2/vendor/pdepend/pdepend/src/main/php/PDepend/Application.php(149): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
     [exec] #9 /home/travis/build/simplesamlphp/saml2/vendor/pdepend/pdepend/src/main/php/PDepend/Application.php(122): PDepend\Application->createContainer()
     [exec] #10 /home/travis/build/simplesamlphp/saml2/vendor/pdepend/pdepend/src/main/php/PDepend/Application.php(92): PDepend\Application->getContainer()
     [exec] #11 /home/travis/build/simplesamlphp/saml2/vendor/phpmd/phpmd/src/main/php/PHPMD/ParserFactory.php(96): PDepend\Application->getEngine()
     [exec] #12 /home/travis/build/simplesamlphp/saml2/vendor/phpmd/phpmd/src/main/php/PHPMD/ParserFactory.php(75): PHPMD\ParserFactory->createInstance()
     [exec] #13 /home/travis/build/simplesamlphp/saml2/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(215): PHPMD\ParserFactory->create()
     [exec] #14 /home/travis/build/simplesamlphp/saml2/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(133): PHPMD\PHPMD->processFiles()
     [exec] #15 /home/travis/build/simplesamlphp/saml2/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(173): PHPMD\TextUI\Command->run()
     [exec] #16 /home/travis/build/simplesamlphp/saml2/vendor/phpmd/phpmd/src/bin/phpmd(122): PHPMD\TextUI\Command::main()
     [exec] #17 {main}
```

We either need to restrict the dependency to 4.1 (quickfix) or resolve the issue

**Comment by KacerCZ** [comment]
Symfony 4 does not support HHVM.
See https://symfony.com/blog/symfony-4-end-of-hhvm-support

**Comment by tvdijen** [comment]
Thanks for pointing this out.. I wasn't aware of that!

I guess the easy way out for me is to stop testing for HVVM, but since PHPmd seems to be abandoned I should probably be looking for alternatives that don't (in)directly rely on Symfony4
