### ISSUE TITLE
Support PHP 8 catching an exception without storing it in a variable

### ISSUE THREAD

**Issue by bperel** [pdepend/pdepend#516]
From PHP 8 it is possible to catch an exception without declaring a variable to store it in. Running pdepend against the following file:
```php
<?php
try {
  $a = 1;
}
catch(Exception) {
  echo 'Something wrong happened';
}
```

outputs the following error:
```
The following error occurred:
Unexpected token: ), line: 5, col: 16, file: /tmp/test.php.
#0 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7227): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7194): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4816): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#3 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3397): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariable()
#4 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3262): PDepend\Source\Language\PHP\AbstractPHPParser->parseCatchStatement()
#5 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5899): PDepend\Source\Language\PHP\AbstractPHPParser->parseTryStatement()
#6 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#7 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#8 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#9 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Runner.php(314): PDepend\Engine->analyze()
#10 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(243): PDepend\TextUI\Runner->run()
#11 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(627): PDepend\TextUI\Command->run()
#12 /srv/vendor/pdepend/pdepend/src/bin/pdepend(72): PDepend\TextUI\Command::main()
#13 {main}
```

**Comment by kylekatarnls** [comment]
Thanks. I will try to see if we can have for the next 2.9.0 which is supposed to support PHP 8.

**Comment by bperel** [comment]
Yes I have seen the other commits related to supporting PHP 8 and this one is the last remaining parsing error on my project if I use the latest commit of pdepend :-)
