### ISSUE TITLE
Character following closing bracket for an array in attributes are producing an Unexpected token error

### ISSUE THREAD

**Issue by cborgas** [pdepend/pdepend#527]
- PHP Depend version: 2.9.0
- PHP Version: 8.0.1
- Installation type: composer
- Operating System / Distribution & Version: AlpineLinux 

### Current Behavior
For the this code in PHP 8 I get the below ERROR when running `phpmd`

Code - Starting at Line 43
```PHP
    #[Route('/thing/{id}', name: 'get_thing_by_id', requirements: ["id" => "\d+"], methods: ['GET'])]
    public function getById(Request $request): Response
    {
        // ...
    }
```

Error
```SHELL
phpmd ./src/ ansi tools/phpmd.xml --suffixes php --execlude */src/Kernel.php

ERROR while parsing
--------------------
Unexpected token: ,, line: 43, col: 86, file: /src/[redacted].php.
#0 /app/tools/ci/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7302): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), Object(PDepend\Source\AST\ASTCompilationUnit))
#1 /app/tools/ci/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(942): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /app/tools/ci/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody(Object(PDepend\Source\AST\ASTClass))
#3 /app/tools/ci/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6055): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#4 /app/tools/ci/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#5 /app/tools/ci/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#6 /app/tools/ci/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#7 /app/tools/ci/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
#8 /app/tools/ci/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(192): PHPMD\Parser->parse(Object(PHPMD\Report))
#9 /app/tools/ci/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(103): PHPMD\PHPMD->processFiles('./src/', 'tools/phpmd.xml', Array, Object(PHPMD\RuleSetFactory))
#10 /app/tools/ci/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(148): PHPMD\TextUI\Command->run(Object(PHPMD\TextUI\CommandLineOptions), Object(PHPMD\RuleSetFactory))
#11 /app/tools/ci/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main(Array)
#12 {main}

Found 0 violations and 1 error in 909ms
```

### Expected Behavior

I expect there to be no error and arrays in attributes are parsed successfully.

### Steps To Reproduce:

1. Create a class method with an attribute that accepts an array as an argument
2. Run phpMD

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment]
Hello 👋 thanks for the report 🙏 it will be fixed in 2.9.1 (#528)
