### ISSUE TITLE
"Unexpected token: =>," when referencing an external constant on left part of match expression

### ISSUE THREAD

**Issue by bperel** [pdepend/pdepend#531]
- PHP Depend version: 2.9.1
- PHP Version: 8.0
- Installation type: (composer)
- Operating System / Distribution & Version: Ubuntu

### Current Behavior
`ERROR while parsing` on the line where a constant is referenced

### Expected Behavior
No parsing error.

### Steps To Reproduce:
Given this file:
```php
<?php
namespace Home;

class A {
    private function getText(string $type): string
    {
        return match ($type) {
            B::C => 'hello'
        };
    }
}
```

When I run `phpmd test.php ansi cleancode`, The following error appears:
```
#0 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7322): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7288): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2014): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#3 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2076): PDepend\Source\Language\PHP\AbstractPHPParser->parseIndexExpression()
#4 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1982): PDepend\Source\Language\PHP\AbstractPHPParser->parseStringIndexExpression()
#5 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4088): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalIndexExpression()
#6 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php(224): PDepend\Source\Language\PHP\AbstractPHPParser->parseFunctionPostfix()
#7 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4030): PDepend\Source\Language\PHP\PHPParserVersion80->parseFunctionPostfix()
#8 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4493): PDepend\Source\Language\PHP\AbstractPHPParser->parseMemberPrefixOrFunctionPostfix()
#9 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2772): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariableOrConstantOrPrimaryPrefix()
#10 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3831): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#11 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3849): PDepend\Source\Language\PHP\AbstractPHPParser->buildReturnStatement()
#12 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6007): PDepend\Source\Language\PHP\AbstractPHPParser->parseReturnStatement()
#13 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5944): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#14 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1278): PDepend\Source\Language\PHP\AbstractPHPParser->parseScope()
#15 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1231): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration()
#16 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(988): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
#17 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(87): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration()
#18 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74->parseMethodOrFieldDeclaration()
#19 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody()
#20 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6075): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#21 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#22 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#23 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#24 /srv/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
#25 /srv/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(192): PHPMD\Parser->parse()
#26 /srv/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(103): PHPMD\PHPMD->processFiles()
#27 /srv/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(148): PHPMD\TextUI\Command->run()
#28 /srv/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
#29 {main}

Found 0 violations and 1 error in 17ms
```

Interestingly, the error doesn't show if I don't specify a namespace at the beginning of the file.

## Checks before submitting
* [ x ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [ x ] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [ x ] I have added every step to reproduce the bug.
* [ x ] If possible I added relevant code examples.
* [ x ] This issue is about 1 bug and nothing more.
* [ x ] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by tvbeek** [comment]
@bperel Thanks for reporting the issue and providing a clear stack trace 👍 

Small question: are you able to provide a fix and/or a PR with a failing test that can be a start for someone to fix it?

**Comment by bperel** [comment]
I'm afraid I don't know anything about how pdepend is written so I can't help on providing a fix.

**Comment by lucassabreu** [comment]
hi, i am having this problem too, the same environment, but it looks to be related to the `namespace`.

running on this does throw an error:
```php
class A {
    private function getText(string $type): string
    {
        return match ($type) {
            B::C => 'hello'
        };
    }
}
```

but with the namespace it will.
