### ISSUE TITLE
Unexpected token ,, for language struct "match"

### ISSUE THREAD

**Issue by vpassapera** [pdepend/pdepend#543]
- PHP Depend version: dev-master (aliasing to 2.9.2)
- PHP Version: 8.0.6
- Installation type: composer
- Operating System / Distribution & Version: Arch Linux

### Current Behavior
```
        return match ($type) {
            'integer', 'double', 'float', 'string', 'object', 'resource', 'boolean' => [$mixed],
            'array' => $mixed,
            default => throw new InvalidTransformationException($type, static::class),
        };
```

Has Error:

```
        -       Unexpected token: ,, line: 679, col: 22, file: /home/vpassapera/Development/PhpTypes/src/Type/Collection.php.
#0 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7394): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7360): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5337): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#3 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php(248): PDepend\Source\Language\PHP\AbstractPHPParser->parseMatchEntry()
#4 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4035): PDepend\Source\Language\PHP\PHPParserVersion80->parseFunctionPostfix()
#5 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4498): PDepend\Source\Language\PHP\AbstractPHPParser->parseMemberPrefixOrFunctionPostfix()
#6 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2777): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariableOrConstantOrPrimaryPrefix()
#7 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3836): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#8 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3854): PDepend\Source\Language\PHP\AbstractPHPParser->buildReturnStatement()
#9 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6065): PDepend\Source\Language\PHP\AbstractPHPParser->parseReturnStatement()
#10 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6002): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#11 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1279): PDepend\Source\Language\PHP\AbstractPHPParser->parseScope()
#12 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1231): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration()
#13 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(988): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
#14 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(87): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration()
#15 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74->parseMethodOrFieldDeclaration()
#16 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody()
#17 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6133): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#18 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#19 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#20 /home/vpassapera/Development/PhpTypes/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#21 /home/vpassapera/Development/PhpTypes/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
#22 /home/vpassapera/Development/PhpTypes/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(240): PHPMD\Parser->parse()
#23 /home/vpassapera/Development/PhpTypes/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(136): PHPMD\PHPMD->processFiles()
#24 /home/vpassapera/Development/PhpTypes/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(184): PHPMD\TextUI\Command->run()
#25 /home/vpassapera/Development/PhpTypes/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
```

### Expected Behavior
Expects multiple values to match a certain condition to be fine, since it is part of the language structure.

### Steps To Reproduce:
Create a match struct like the one in the example. Run phpmd.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment]
Confirmed, there is a mistake at this point:
https://github.com/pdepend/pdepend/blob/c64d932f9429c31519c386139e41f6b1f68813c7/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php#L5335

It should loop as long as a coma is found and add the next expression as a key.

Then it implies users to consider `ASTMatchEntry` may contains more than 2 children, and value is always the last one. But this point should not be an issue yet and would not be considered as a BC.
