### ISSUE TITLE
PHP 8 new with arbitrary expressions leads to a syntax issue

### ISSUE THREAD

**Issue by tvbeek** [pdepend/pdepend#601]
This is reported by @Geolim4 in https://github.com/phpmd/phpmd/issues/952

- PHP Depend version: 2.10.2
- PHP Version: 8.0.2
- Installation type: composer
- Operating System / Distribution & Version: -

### Current Behavior

This (valid) code:
```
$myObject = new (SomeArbitraryCode::class . 'loremIpsum' . trim(' Hello '))($arg1, $arg2);
```
Leads to the following error:

```
Unexpected token: (, line: xx, col: xx, file: xxxxxxxxxxx.php.
#0 xxxxxxxxxxx\vendor\pdepend\pdepend\src\main\php\PDepend\Source\Language\PHP\AbstractPHPParser.php(7844): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), Object(PDepend\Source\AST\ASTCompilationUnit)
)
```

### Expected Behavior
No error, dynamic class instantiation has been introduced as of PHP 8:
https://www.php.net/manual/en/language.oop5.basic.php

### Steps To Reproduce:
Just analyses the piece of code above.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by Geolim4** [comment]
Hello @tvbeek do you have any ETA on this issue ? So I can prepare things on my side depending ETA :)

Thank you !

**Comment by AJenbo** [comment]
@Geolim4 are you asking when the issue will be resolved (unknown) or are you offering to work on it?

**Comment by Geolim4** [comment]
> @Geolim4 are you asking when the issue will be resolved (unknown) or are you offering to work on it? 

I really would like on solve this issue, but this project is way too complex for me and lexer project like this are particularly complex. 
No I'm working on a core update of Phpfastcache and I'd like to use arbitrary expression constructors, but until MD is patched, I can't push it to the CI. But no rush, nothing, I just want an approximate ETA so I can prepare my schedule :D

**Comment by tvbeek** [comment]
I was confused by the complex building of the class name. But that isn't the problem, the problem is the new with (...)

```php
<?php
$class = 'stdClass';

// this is no problem
$object1 = new $class;

// this result in an error.
$object2 = new ($class);

// this will also result in an error
$object3 = new ('stdClass');
```

```log
The following error occurred:
Unexpected token: (, line: 8, col: 16, file: /home/tvbeek/projects/temp/test3.php.
#0 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7882): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7849): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6828): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#3 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6757): PDepend\Source\Language\PHP\AbstractPHPParser->parseQualifiedNameRaw()
#4 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2666): PDepend\Source\Language\PHP\AbstractPHPParser->parseQualifiedName()
#5 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2445): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassOrInterfaceReference()
#6 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2466): PDepend\Source\Language\PHP\AbstractPHPParser->parseStandAloneExpressionTypeReference()
#7 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1727): PDepend\Source\Language\PHP\AbstractPHPParser->parseExpressionTypeReference()
#8 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(346): PDepend\Source\Language\PHP\AbstractPHPParser->parseAllocationExpressionTypeReference()
#9 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1705): PDepend\Source\Language\PHP\PHPParserVersion70->parseAllocationExpressionTypeReference()
#10 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3034): PDepend\Source\Language\PHP\AbstractPHPParser->parseAllocationExpression()
#11 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4904): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#12 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3148): PDepend\Source\Language\PHP\AbstractPHPParser->parseAssignmentExpression()
#13 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6586): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#14 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(507): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#15 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Engine.php(606): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#16 /home/tvbeek/projects/pdepend/src/main/php/PDepend/Engine.php(351): PDepend\Engine->performParseProcess()
#17 /home/tvbeek/projects/pdepend/src/main/php/PDepend/TextUI/Runner.php(322): PDepend\Engine->analyze()
#18 /home/tvbeek/projects/pdepend/src/main/php/PDepend/TextUI/Command.php(246): PDepend\TextUI\Runner->run()
#19 /home/tvbeek/projects/pdepend/src/main/php/PDepend/TextUI/Command.php(630): PDepend\TextUI\Command->run()
#20 /home/tvbeek/projects/pdepend/src/bin/pdepend(72): PDepend\TextUI\Command::main()
#21 {main}
```

I didn't yet have the solution but have this to prevent anyone to get distracted by the same part.

**Comment by Geolim4** [comment]
Thanks !
