### ISSUE TITLE
Unexpected token error when a variable is used as a key in array destructuring

### ISSUE THREAD

**Issue by elchenberg** [pdepend/pdepend#602]
- PHP Depend version: 2.10.3
- PHP Version: 7.3.33, 7.4.30, 8.1.7, 8.1.8
- Installation type: composer
- Operating System / Distribution & Version: Alpine Linux v3.15, Debian GNU/Linux 11 (bullseye)

### Current Behavior

When a variable (or a constant) is used as a key in array destructuring PHP Depend throws an "Unexpected token" error.

### Expected Behavior

No `Unexpected token` error

### Steps To Reproduce:

Code:

```php
<?php
$foo = [['bug' => 'test']];
$key = 'bug';
foreach ($foo as [$key => $bar]) {
    var_dump($bar);
};
```

Command: `php vendor/bin/pdepend --summary-xml=/dev/null bug.php`

PHP Depend output:

```text
PDepend 2.10.3

Parsing source files:
.                                                                1

Calculating Cyclomatic Complexity metrics:
.     0

Calculating Node Loc metrics:
.     0

Calculating NPath Complexity metrics:
.     0

Calculating Inheritance metrics:
.     0

Calculating Node Count metrics:
.     0

Calculating Hierarchy metrics:
.     0

Calculating Code Rank metrics:
.     0

Calculating Coupling metrics:
.     0

Calculating Class Level metrics:
.     0

Calculating Cohesion metrics:
.     0

Calculating Halstead metrics:
.     0

Calculating Maintainability Index metrics:
.     0

Generating pdepend log files, this may take a moment.

The following error occurred:
Unexpected token: =>, line: 4, col: 24, file: /workdir/bug.php.
#0 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7844): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), Object(PDepend\Source\AST\ASTCompilationUnit))
#1 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4814): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1869): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariableOrConstantOrPrimaryPrefix()
#3 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1833): PDepend\Source\Language\PHP\AbstractPHPParser->parseListSlotExpression()
#4 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3905): PDepend\Source\Language\PHP\AbstractPHPParser->parseListExpression()
#5 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3945): PDepend\Source\Language\PHP\AbstractPHPParser->parseForeachChildren()
#6 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6472): PDepend\Source\Language\PHP\AbstractPHPParser->parseForeachStatement()
#7 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(483): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#8 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(606): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#9 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(351): PDepend\Engine->performParseProcess()
#10 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Runner.php(322): PDepend\Engine->analyze()
#11 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(246): PDepend\TextUI\Runner->run()
#12 /workdir/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(630): PDepend\TextUI\Command->run()
#13 /workdir/vendor/pdepend/pdepend/src/bin/pdepend(72): PDepend\TextUI\Command::main()
#14 /workdir/vendor/bin/pdepend(120): include('/workdir/vendor...')
#15 {main}


Time: 0:00:00; Memory: 6.00Mb
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by tvbeek** [comment]
I never have thought about using this in a foreach, but it is possible so we shouldn't crash on it.

**Comment by kylekatarnls** [comment]
I will investigate this bug. For the record and implementation in the correct parser, this syntax is allowed since PHP 7.1.
