### ISSUE TITLE
GlobalBuilderContext::registerClass() should accept ASTEnum class or an relevant interface. 

### ISSUE THREAD

**Issue by lisfox1** [pdepend/pdepend#621]
- PHP Depend version: 2.11.0
- PHP Version: 8.1.9
- Installation type: composer
- Operating System / Distribution & Version: macOS Monterey Version 12.1

### Current Behavior
When trying to unserialize `PDepend\Source\AST\ASTEnum` class I am getting a type error due to the `PDepend\Source\Builder\BuilderContext\GlobalBuilderContext::registerClass()` expecting `PDepend\Source\AST\ASTClass` and the magic funtion `PDepend\Source\AST\ASTEnum::__wakup` is passing `PDepend\Source\AST\ASTEnum`. 
The error is as follow
```
TypeError : PDepend\Source\Builder\BuilderContext\GlobalBuilderContext::registerClass(): Argument #1 ($class) must be of type PDepend\Source\AST\ASTClass, PDepend\Source\AST\ASTEnum given, called in /###/###/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTEnum.php on line 291
```

### Expected Behavior
I am expecting the class to get unserialize

### Steps To Reproduce:
```
$class = new \PDepend\Source\AST\ASTEnum('test', new \PDepend\Source\AST\ASTScalarType('string'));
$class->setCache(new \PDepend\Util\Cache\Driver\MemoryCacheDriver());
$class->setContext(new \PDepend\Source\Builder\BuilderContext\GlobalBuilderContext(new \PDepend\Source\Language\PHP\PHPBuilder()));
$serializedClass = serialize($class);
unserialize($serializedClass);
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by chelsEg** [comment]
I have the same error:

```
PHP Fatal error:  Uncaught TypeError: PDepend\Metrics\Analyzer\HierarchyAnalyzer::visitClass(): Argument #1 ($class) must be of type PDepend\Source\AST\ASTClass, PDepend\Source\AST\ASTEnum given, called in /application/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTEnum.php on line 274 and defined in /application/vendor/pdepend/pdepend/src/main/php/PDepend/Metrics/Analyzer/HierarchyAnalyzer.php:215
Stack trace:
#0 /application/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTEnum.php(274): PDepend\Metrics\Analyzer\HierarchyAnalyzer->visitClass(Object(PDepend\Source\AST\ASTEnum))
#1 /application/vendor/pdepend/pdepend/src/main/php/PDepend/Metrics/Analyzer/HierarchyAnalyzer.php(302): PDepend\Source\AST\ASTEnum->accept(Object(PDepend\Metrics\Analyzer\HierarchyAnalyzer))
#2 /application/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTNamespace.php(328): PDepend\Metrics\Analyzer\HierarchyAnalyzer->visitNamespace(Object(PDepend\Source\AST\ASTNamespace))
#3 /application/vendor/pdepend/pdepend/src/main/php/PDepend/Metrics/Analyzer/HierarchyAnalyzer.php(170): PDepend\Source\AST\ASTNamespace->accept(Object(PDepend\Metrics\Analyzer\HierarchyAnalyzer))
#4 /application/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(639): PDepend\Metrics\Analyzer\HierarchyAnalyzer->analyze(Object(PDepend\Source\AST\ASTArtifactList))
#5 /application/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(359): PDepend\Engine->performAnalyzeProcess()
#6 /application/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
#7 /application/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(240): PHPMD\Parser->parse(Object(PHPMD\Report))
#8 /application/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(136): PHPMD\PHPMD->processFiles('./app', './phpmd.xml', Array, Object(PHPMD\RuleSetFactory), Object(PHPMD\Report))
#9 /application/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(184): PHPMD\TextUI\Command->run(Object(PHPMD\TextUI\CommandLineOptions), Object(PHPMD\RuleSetFactory))
#10 /application/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main(Array)
#11 /application/vendor/bin/phpmd(117): include('/application/ve...')
#12 {main}
  thrown in /application/vendor/pdepend/pdepend/src/main/php/PDepend/Metrics/Analyzer/HierarchyAnalyzer.php on line 215
```

- PHP Depend version: 2.11.0
- PHP Version: 8.1.9
- Installation type: composer
- Operating System / Distribution & Version: macOS Monterey Version 12.5.1

**Comment by kylekatarnls** [comment]
Hello, I'm working on a fix, you can try it with `composer require pdepend/pdepend:dev-fix/issue-621-enum-serialization`
