### ISSUE TITLE
PHP 8.1 : Unexpected token: :, with Enum

### ISSUE THREAD

**Issue by dimitriBouteille** [pdepend/pdepend#650]
- PHP Depend version: 2.12.1
- PHP Version: 8.1
- Installation type: composer
- Operating System / Distribution & Version: Linux

### Current Behavior

When I want to analyze the following code with phpMD, I have the following error: `Unexpected token: :, line: 25, col: 18, file: .../Model/Config/Source/ShippingLogo.php.`

**Full error trace :**  

```txt
-	Unexpected token: :, line: 25, col: 18, file: ../Model/Config/Source/ShippingLogo.php.
#0 /home/web/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7440): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 /home/web/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7406): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /home/web/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6210): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#3 /home/web/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3262): PDepend\Source\Language\PHP\AbstractPHPParser->parseNonePhpCode()
#4 /home/web/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6196): PDepend\Source\Language\PHP\AbstractPHPParser->parseStatementTermination()
#5 /home/web/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#6 /home/web/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#7 /home/web/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#8 /home/web/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
#9 /home/web/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(240): PHPMD\Parser->parse()
#10 /home/web/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(136): PHPMD\PHPMD->processFiles()
#11 /home/web/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(184): PHPMD\TextUI\Command->run()
#12 /home/web/.composer/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
#13 {main}
```

**The code :** 

```php
<?php
/**
 * 2001-2023 XXX
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to XXX so we can send you a copy immediately.
 *
 * @author XXX
 * @copyright 2001-2023 XXX
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
declare(strict_types=1);

namespace Reflet\EInvoice\Model\Config\Source;

/**
 * Class ModeProvider
 *
 * @package Reflet\EInvoice\Model\Config\Source
 */
enum ModeProvider: string
{

    case Donation = 'donation';
    case Default = 'default';

    /**
     * @return \Magento\Framework\Phrase
     * @throws \Exception
     */
    public function label(): \Magento\Framework\Phrase
    {
        return match($this) {
            self::Donation => __('Donation'),
            self::Default => __('E-Invoice'),
        };
    }
}
```

### Expected Behavior

There should normally be no error with the code mentioned just before.

**Comment by kylekatarnls** [comment]
I just tested, this will also be fixed by #656 in the next release.
