### ISSUE TITLE
Use of "Parent" in namespace triggers "Unexpected token: Parent".

### ISSUE THREAD

**Issue by jmfeurprier** [pdepend/pdepend#709]
- PHP Depend version: 2.16.2
- PHP Version: 8.3.2
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu 22.04.3 LTS

### Current Behavior
"parent" is a [reserved keyword for class names](https://www.php.net/manual/en/reserved.classes.php), but not for namespaces.
PHP is ok with a class such as "App\Parent\ParentResolver", but PHP Depend does not support it.

### Expected Behavior
Let "Parent" be used as a namespace token.

### Steps To Reproduce:
Given a class as this one:
```
<?php

namespace App\Parent;

class ParentResolver
{
}
```

Running:
`vendor/bin/pdepend --jdepend-chart=jdepend.svg ParentResolver.php`

Will output:
```
PDepend 2.16.2

Parsing source files:
.                                                                1

Calculating Dependency metrics:
.     0

Generating pdepend log files, this may take a moment.

The following error occurred:
Unexpected token: Parent, line: 3, col: 15, file: [...]/ParentResolver.php.
#0 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8056): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8041): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(613): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedNextTokenException()
#3 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6996): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassName()
#4 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(601): PDepend\Source\Language\PHP\AbstractPHPParser->parseQualifiedNameElement()
#5 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6963): PDepend\Source\Language\PHP\PHPParserVersion70->parseQualifiedNameElement()
#6 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6886): PDepend\Source\Language\PHP\AbstractPHPParser->parseQualifiedNameRaw()
#7 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7021): PDepend\Source\Language\PHP\AbstractPHPParser->parseQualifiedName()
#8 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(503): PDepend\Source\Language\PHP\AbstractPHPParser->parseNamespaceDeclaration()
#9 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(607): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#10 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(352): PDepend\Engine->performParseProcess()
#11 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Runner.php(322): PDepend\Engine->analyze()
#12 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(246): PDepend\TextUI\Runner->run()
#13 [...]/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(639): PDepend\TextUI\Command->run()
#14 [...]/vendor/pdepend/pdepend/src/bin/pdepend(72): PDepend\TextUI\Command::main()
#15 [...]/vendor/bin/pdepend(119): include('...')
#16 {main}


Time: 0:00:00; Memory: 12.00Mb
```

Thanks for the great tool!

**Comment by AJenbo** [comment]
Duplicate of https://github.com/pdepend/pdepend/issues/889
