### ISSUE TITLE
`Unexpected token: |` when using union typed constants

### ISSUE THREAD

**Issue by ToshY** [pdepend/pdepend#712]
- PHP Depend version: `2.16.2` (through PHPMD version: `2.15.0`)
- PHP Version: `8.3.2`
- Installation type: `composer`
- Operating System / Distribution & Version: `Ubuntu 22.0.4 LTS (WSL2)`

### Current Behavior

I've found this problem through using PHPMD [2.15.0](https://github.com/phpmd/phpmd/releases/tag/2.15.0), but looking at stacktrace it seems to be a problem with PHP Depend.

The following stacktrace is shown when executing phpmd, having used union typed constants in classes.

```console
-       Unexpected token: |, line: 13, col: 24, file: /app/src/ExampleClass.php.
#0 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8056): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), Object(PDepend\Source\AST\ASTCompilationUnit))
#1 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8041): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException(Object(PDepend\Source\Tokenizer\Token))
#2 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8006): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedNextTokenException()
#3 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7264): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken(19)
#4 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7177): PDepend\Source\Language\PHP\AbstractPHPParser->parseConstantDeclarator()
#5 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php(138): PDepend\Source\Language\PHP\AbstractPHPParser->parseConstantDefinition()
#6 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(107): PDepend\Source\Language\PHP\PHPParserVersion71->parseUnknownDeclaration(47, 1)
#7 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1187): PDepend\Source\Language\PHP\PHPParserVersion74->parseUnknownDeclaration(47, 1)
#8 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1056): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration(1)
#9 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion81.php(156): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody(Object(PDepend\Source\AST\ASTEnum))
#10 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6637): PDepend\Source\Language\PHP\PHPParserVersion81->parseEnumDeclaration()
#11 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(516): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#12 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(607): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#13 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(352): PDepend\Engine->performParseProcess()
#14 /app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(99): PDepend\Engine->analyze()
#15 /app/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(264): PHPMD\Parser->parse(Object(PHPMD\Report))
#16 /app/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(160): PHPMD\PHPMD->processFiles('src/ExampleClass...', Array, Array, Array, Object(PHPMD\Report))
#17 /app/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(222): PHPMD\TextUI\Command->run(Object(PHPMD\TextUI\CommandLineOptions), Object(PHPMD\RuleSetFactory))
#18 /app/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main(Array)
#19 /app/vendor/bin/phpmd(119): include('/app/vendor/php...')
#20 {main}
```

### Expected Behavior

No error.

### Steps To Reproduce:

1. Create a class with public const having an union type.

```php
<?php

declare(strict_types=1);

enum ExampleClass {
    public const string|int VALUE = 5;
}
```

```php
<?php

declare(strict_types=1);

class ExampleClass {
    public const string|int VALUE = 5;
}
```

2. Run PHPMD on it.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

---

Related #692

**Comment by tvbeek** [comment]
@ToshY thanks for reporting!

Small question, do you have the option to create a PR with a fix?

**Comment by ToshY** [comment]
Hey @tvbeek 👋 

Well I can try for sure. I can't really say right now howlong it will take me to understand it and fix it, so if you don't mind that I can give it a shot. 

Are there any contribution guidelines I should take into consideration?

**Comment by AJenbo** [comment]
Try to avoid backwards breaking changes, remember to use 5.3 syntax and follow the code style as best you can. We will try to help you with any issue you run in to.

**Comment by ToshY** [comment]
Oh forgot to close this after it was merged 🤦‍♂️ 

Any indication for when the next tag/release will be available?
