### ISSUE TITLE
"Unexpected token: [" error when accessing array constant item

### ISSUE THREAD

**Issue by prudloff-insite** [pdepend/pdepend#713]
- PHP Depend version: 2.16.2
- PHP Version: 8.1.8
- Installation type: composer
- Operating System / Distribution & Version: Debian 11

### Current Behavior
```
Unexpected token: [, line: 23, col: 18, file: /var/www/web/modules/custom/extranet_odoo_user_sync/src/URComputedField.php.
#0 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8056): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), Object(PDepend\Source\AST\ASTCompilationUnit))
#1 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8041): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException(Object(PDepend\Source\Tokenizer\Token))
#2 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8006): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedNextTokenException()
#3 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2495): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken(7)
#4 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3157): PDepend\Source\Language\PHP\AbstractPHPParser->parseIssetExpression()
#5 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2823): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#6 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(275): PDepend\Source\Language\PHP\AbstractPHPParser->parseBraceExpression(Object(PDepend\Source\AST\ASTExpression), Object(PDepend\Source\Tokenizer\Token), 7, 118)
#7 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3856): PDepend\Source\Language\PHP\PHPParserVersion70->parseParenthesisExpression()
#8 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6609): PDepend\Source\Language\PHP\AbstractPHPParser->parseIfStatement()
#9 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6557): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#10 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1476): PDepend\Source\Language\PHP\AbstractPHPParser->parseScope()
#11 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1428): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration(Object(PDepend\Source\AST\ASTMethod))
#12 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1174): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
#13 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1057): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration(2)
#14 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(857): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody(Object(PDepend\Source\AST\ASTClass))
#15 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6702): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#16 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(516): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#17 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(607): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#18 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(352): PDepend\Engine->performParseProcess()
#19 /var/www/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(99): PDepend\Engine->analyze()
#20 /var/www/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(264): PHPMD\Parser->parse(Object(PHPMD\Report))
#21 /var/www/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(165): PHPMD\PHPMD->processFiles('RoboFile.php,co...', Array, Array, Array, Object(PHPMD\Report))
#22 /var/www/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(222): PHPMD\TextUI\Command->run(Object(PHPMD\TextUI\CommandLineOptions), Object(PHPMD\RuleSetFactory))
#23 /var/www/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main(Array)
#24 /var/www/vendor/bin/phpmd(120): include('/var/www/vendor...')
#25 {main}
```

### Expected Behavior
No error.

### Steps To Reproduce:
Run phpmd 2.15.0 on a class with a method containing this code:

```php
    define('FOO', []);

    if (isset(FOO['foo'])) {

    }
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by tvbeek** [comment]
@prudloff-insite thanks for the report, this is a nice catch.

Small question, do you have an option to try to create a PR for a fix or not?

**Comment by prudloff-insite** [comment]
Unfortunately, I don't think I know enough about how pdepend work to write a PR.

**Comment by AJenbo** [comment]
Not an issue in 3.x

**Comment by AJenbo** [comment]
@prudloff-insite even just adding a failing test (or successful if the issue was already solved) would be a big help
