### ISSUE TITLE
Unexpected token with anonymous readonly class

### ISSUE THREAD

**Issue by pawel-slowik** [pdepend/pdepend#888]
- PHP Depend version: 2.16.2, also tried dev-master / 058c4a9
- PHP Version: 8.3.12
- Installation type: composer
- Operating System / Distribution & Version: official PHP Docker image, Alpine variant - `php:8.3-alpine`

### Current Behavior
An anonymous readonly class in the analyzed code causes pdepend to crash with `Unexpected token` message.

### Expected Behavior
No crash.

### Steps To Reproduce:

Create a file with the following content:
```php
<?php

$foo = new readonly class () {};

var_dump($foo);
```

Attempt to analyze it:
```shell
./vendor/bin/pdepend --summary-xml=summary.xml test.php
```

Result:
```
The following error occurred:
Unexpected token: class, line: 3, col: 21, file: /app/test.php.
#0 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8070): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), Object(PDepend\Source\AST\ASTCompilationUnit))
#1 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(8055): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException(Object(PDepend\Source\Tokenizer\Token))
#2 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3381): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedNextTokenException()
#3 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion54.php(313): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpressionForVersion()
#4 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion56.php(303): PDepend\Source\Language\PHP\PHPParserVersion54->parseOptionalExpressionForVersion()
#5 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(461): PDepend\Source\Language\PHP\PHPParserVersion56->parseOptionalExpressionForVersion()
#6 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php(141): PDepend\Source\Language\PHP\PHPParserVersion70->parseOptionalExpressionForVersion()
#7 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3340): PDepend\Source\Language\PHP\PHPParserVersion80->parseOptionalExpressionForVersion()
#8 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5026): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#9 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3265): PDepend\Source\Language\PHP\AbstractPHPParser->parseAssignmentExpression(Object(PDepend\Source\AST\ASTVariable))
#10 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6726): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#11 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(516): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#12 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(607): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#13 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(352): PDepend\Engine->performParseProcess()
#14 /app/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Runner.php(322): PDepend\Engine->analyze()
#15 /app/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(246): PDepend\TextUI\Runner->run()
#16 /app/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(639): PDepend\TextUI\Command->run()
#17 /app/vendor/pdepend/pdepend/src/bin/pdepend(72): PDepend\TextUI\Command::main()
#18 /app/vendor/bin/pdepend(119): include('/app/vendor/pde...')
#19 {main}
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by AJenbo** [comment]
Could you please test the 3.x branch

**Comment by pawel-slowik** [comment]
Thank you for the swift response.
Unfortunately the problem persists on the 3.x branch / commit f8300ed .

```
Unexpected token: class, line: 3, col: 21, file: /app/test.php.
#0 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8741): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), '/app/test.php')
#1 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8728): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException(Object(PDepend\Source\Tokenizer\Token))
#2 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(3635): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedNextTokenException()
#3 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(3567): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpressionForVersion()
#4 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(5266): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#5 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(3484): PDepend\Source\Language\PHP\AbstractPHPParser->parseAssignmentExpression(Object(PDepend\Source\AST\ASTVariable))
#6 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(7145): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#7 /app/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(734): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#8 /app/vendor/pdepend/pdepend/src/Engine.php(529): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#9 /app/vendor/pdepend/pdepend/src/Engine.php(288): PDepend\Engine->performParseProcess()
#10 /app/vendor/pdepend/pdepend/src/TextUI/Runner.php(283): PDepend\Engine->analyze()
#11 /app/vendor/pdepend/pdepend/src/TextUI/Command.php(240): PDepend\TextUI\Runner->run()
#12 /app/vendor/pdepend/pdepend/src/TextUI/Command.php(604): PDepend\TextUI\Command->run()
#13 /app/vendor/pdepend/pdepend/bin/pdepend(72): PDepend\TextUI\Command::main()
#14 /app/vendor/bin/pdepend(119): include('/app/vendor/pde...')
#15 {main}
```
